Termin = new Array()


Termin[Termin.length]='September 14, 2016';
Termin[Termin.length]='<div id="event_title1"><b>Bogenschie&szlig;en an der Steinzeitwerkstatt</b><br>ab 16.00 Uhr</div><div id="event_text1"><br>F&uuml;r alle ehemaligen Teilnehmer der klassischen Bogenbauseminare in der Steinzeitwerkstatt bietet Dr. Johann Tinnes in den Sommermonaten alle zwei Wochen -immer mittwochs- die M&ouml;glichkeit zum freien Bogenschie&szlig;en an. Die Bogensch&uuml;tzen treffen sich um 16 Uhr an der Steinzeitwerkstatt. Die Teilnahme ist kostenlos.</div>';

Termin[Termin.length]='September 17, 2016';
Termin[Termin.length]='<div id="event_title2"><b>Bogenbauworkshop</b><br>09.00-18.00 Uhr</div><div id="event_text2"><br>Der Kursleiter Dr. Johann Tinnes baut seit vielen Jahren B&ouml;gen, Pfeile und Zubeh&ouml;r nach arch&auml;ologischen sowie v&ouml;lkerkundlichen Vorbildern und arbeitet f&uuml;r zahlreiche Museen.<br>In diesem Kurs besteht die M&ouml;glichkeit einen Bogen und zwei Pfeile unter fachkundiger Anleitung selber herzustellen. F&uuml;r die B&ouml;gen wird in der Regel Hickoryholz verwendet, f&uuml;r die Pfeile Kiefer oder Zeder (je nach Verf&uuml;gbarkeit). Zudem wird es eine Einf&uuml;hrung in die Handhabung des Bogens und ein Einschie&szlig;en geben.<br>Das Programm findet jeweils Samstag und Sonntag von 09.00 bis 18.00 Uhr statt.<br>Kosten: 200 &euro; bis 350 &euro;, abh&auml;ngig vom Bogentyp<br>Anmeldung: 0221.513877 / 0172.2435593, j.tinnes.pre-rec@arcor.de<br>Weitere Infos: http://www.pre-rec.de/index.html</div>';

Termin[Termin.length]='September 18, 2016';
Termin[Termin.length]='<div id="event_title3"><b>Bogenbauworkshop</b><br>09.00-18.00 Uhr</div><div id="event_text3"><br>Der Kursleiter Dr. Johann Tinnes baut seit vielen Jahren B&ouml;gen, Pfeile und Zubeh&ouml;r nach arch&auml;ologischen sowie v&ouml;lkerkundlichen Vorbildern und arbeitet f&uuml;r zahlreiche Museen.<br>In diesem Kurs besteht die M&ouml;glichkeit einen Bogen und zwei Pfeile unter fachkundiger Anleitung selber herzustellen. F&uuml;r die B&ouml;gen wird in der Regel Hickoryholz verwendet, f&uuml;r die Pfeile Kiefer oder Zeder (je nach Verf&uuml;gbarkeit). Zudem wird es eine Einf&uuml;hrung in die Handhabung des Bogens und ein Einschie&szlig;en geben.<br>Das Programm findet jeweils Samstag und Sonntag von 09.00 bis 18.00 Uhr statt.<br>Kosten: 200 &euro; bis 350 &euro;, abh&auml;ngig vom Bogentyp<br>Anmeldung: 0221.513877 / 0172.2435593, j.tinnes.pre-rec@arcor.de<br>Weitere Infos: http://www.pre-rec.de/index.html</div>';

Termin[Termin.length]='September 25, 2016';
Termin[Termin.length]='<div id="event_title4"><b>Entenmarsch-Familienf&uuml;hrung</b><br>14.00-15.00 Uhr</div><div id="event_text4"><br>Lernen Sie bei einer am&uuml;santen Reise in die Parallelwelt der Enten die spannende Kultur unserer gefiederten Freunde kennen. Sie werden dabei auf erstaunliche &Auml;hnlichkeiten mit der menschlichen Geschichte sto&szlig;en.<br>Kosten: 3 &euro; + Eintritt, VVK an der Museumskasse oder online zzgl. Geb&uuml;hren</div>';

Termin[Termin.length]='September 28, 2016';
Termin[Termin.length]='<div id="event_title5"><b>Bogenschie&szlig;en an der Steinzeitwerkstatt</b><br>ab 16.00 Uhr</div><div id="event_text5"><br>F&uuml;r alle ehemaligen Teilnehmer der klassischen Bogenbauseminare in der Steinzeitwerkstatt bietet Dr. Johann Tinnes in den Sommermonaten alle zwei Wochen -immer mittwochs- die M&ouml;glichkeit zum freien Bogenschie&szlig;en an. Die Bogensch&uuml;tzen treffen sich um 16 Uhr an der Steinzeitwerkstatt. Die Teilnahme ist kostenlos.</div>';

Termin[Termin.length]='October 07, 2016';
Termin[Termin.length]='<div id="event_title6"><b>DoggyDay</b><br>14.00-18.00 Uhr</div><div id="event_text6"><br>Hunde an der Leine mit gut erzogenen Haltern k&ouml;nnen die Dauerausstellung erkunden. Auch im Museumscafé werden Hund und Halter gerne empfangen.<br>Die Teilnahme am „DoggyDay“ kostet 2 &euro; je Hund zzgl. Eintritt f&uuml;r den Halter.</div>';

Termin[Termin.length]='October 12, 2016';
Termin[Termin.length]='<div id="event_title7"><b>Mitmachf&uuml;hrung in der Dauerausstellung</b><br>12.00-13.00 Uhr</div><div id="event_text7"><br>Kommt mit zu den Neanderthalern. Wir besuchen sie an ihrem Lagerplatz und lernen die eiszeitlichen J&auml;ger und Sammler n&auml;her kennen. Wir sehen, welche Werkzeuge und Waffen sie benutzt haben, was ihre Lieblingsspeisen war, und welches Kleider sie getragen haben.<br>Das Beste an dieser Mitmachf&uuml;hrung ist aber zweifellos, dass ihr viele Objekte, beispielsweise einen echten Mammutzahn, in die Hand nehmen und untersuchen d&uuml;rft.<br>Treffpunkt: Eingangsfoyer des Neanderthal Museums F&uuml;r Kinder ab 6 Jahre, Dauer: 1 Stunde<br>Den Eintritt zahlt ihr direkt an der Museumskasse, die 4 &euro; f&uuml;r die F&uuml;hrung zahlt ihr bei der P&auml;dagogin/dem P&auml;dagogen.<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 12, 2016';
Termin[Termin.length]='<div id="event_title8"><b>Steinzeit-Krimi</b><br>14.00-16.00 Uhr</div><div id="event_text8"><br>Ein fr&uuml;hmenschlicher Sch&auml;del wurde aus dem Museum gestohlen. Gemeinsam nehmt ihr die Ermittlungen nach der Diebesbande auf. Wer k&ouml;nnte das wertvolle St&uuml;ck gestohlen haben und wo befindet es sich jetzt? Die Mitarbeiter sind verzweifelt. K&ouml;nnt ihr helfen? Bei der interaktiven Verbrecherjagd m&uuml;ssen Spuren untersucht, knifflige R&auml;tsel gel&ouml;st und alle Hinweise schlau kombiniert werden. Eure Nachforschungen f&uuml;hren euch vom Museum und &uuml;ber das Au&szlig;engel&auml;nde durch den Wald zum spannenden Showdown. Ob ihr das Verbrechen aufkl&auml;ren k&ouml;nnt?<br>Treffpunkt: Eingangsfoyer des Neanderthal Museums F&uuml;r Kinder ab 8/9 Jahre, Dauer: 2 Stunden<br>Kosten: 16 &euro; inkl. Material und Eintritt<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 13, 2016';
Termin[Termin.length]='<div id="event_title9"><b>Feuerstein - Schatz der Steinzeit</b><br>14.00-16.00 Uhr</div><div id="event_text9"><br>Ein Feuerstein war in der Steinzeit ein gro&szlig;er Schatz! Die Menschen stellten daraus wertvolle Werkzeuge und Waffen her, ohne die ihr &Uuml;berleben sicherlich deutlich schwerer gewesen w&auml;re. Mit Feuersteinen konnte man nicht nur Feuer machen, sondern auch Fell, Leder oder andere harte Materialien durchtrennen. Ihr lernt all diese M&ouml;glichkeiten des Feuersteins kennen, fertigt ein Steinzeitmesser an und graviert mit dem Feuerstein Bilder in Schiefer. Die Schieferplatte und das Steinzeitmesser k&ouml;nnt ihr mit nach Hause nehmen.<br>Treffpunkt: Steinzeitwerkstatt, F&uuml;r Kinder ab 8 Jahre, Dauer: 2 Stunde<br>Kosten: 16 &euro; inklusive Material<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 14, 2016';
Termin[Termin.length]='<div id="event_title10"><b>Steinzeittag</b><br>11.00-14.00 Uhr</div><div id="event_text10"><br>Wir machen mit euch eine Zeitreise in die Steinzeit. Wir besuchen die Neanderthaler im Museum und sehen, wie die damaligen Menschen gelebt haben. Dann geht es durch den Wald zur Steinzeitwerkstatt, wo ihr das steinzeitliche Jagen mit Speeren ausprobiert und N&uuml;sse knacken lernt.<br>Nach einer kleinen Pause, in der ihr euch mit euren mitgebrachten Broten und Getr&auml;nken st&auml;rken k&ouml;nnt, stellen wir ein steinzeitliches Amulett aus Leder, einer Knochenperle und einer Muschel her. Das Amulett k&ouml;nnt ihr zur Erinnerung mit nach Hause nehmen.<br>reffpunkt: Eingangsfoyer des Neanderthal Museums, F&uuml;r Kinder ab 6 Jahre<br>Kosten: 24 &euro; inkl. Material und Eintritt<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 14, 2016';
Termin[Termin.length]='<div id="event_title11"><b>Museumsnacht</b><br>14.00-15.00 Uhr</div><div id="event_text11"><br>Das gesamte Haus inklusive Sonderausstellung und Café sind ge&ouml;ffnet. Besuchen Sie bei freiem Eintritt die neu gestalteten Museumsbereiche.</div>';

Termin[Termin.length]='October 18, 2016';
Termin[Termin.length]='<div id="event_title12"><b>Mitmachf&uuml;hrung in der Dauerausstellung</b><br>14.00-15.00 Uhr</div><div id="event_text12"><br>Kommt mit zu den Neanderthalern. Wir besuchen sie an ihrem Lagerplatz und lernen die eiszeitlichen J&auml;ger und Sammler n&auml;her kennen. Wir sehen, welche Werkzeuge und Waffen sie benutzt haben, was ihre Lieblingsspeisen war, und welches Kleider sie getragen haben.<br>Das Beste an dieser Mitmachf&uuml;hrung ist aber zweifellos, dass ihr viele Objekte, beispielsweise einen echten Mammutzahn, in die Hand nehmen und untersuchen d&uuml;rft.<br>Treffpunkt: Eingangsfoyer des Neanderthal Museums F&uuml;r Kinder ab 6 Jahre, Dauer: 1 Stunde<br>Den Eintritt zahlt ihr direkt an der Museumskasse, die 4 &euro; f&uuml;r die F&uuml;hrung zahlt ihr bei der P&auml;dagogin/dem P&auml;dagogen.<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 19, 2016';
Termin[Termin.length]='<div id="event_title13"><b>Steinzeittag</b><br>13.00-16.00 Uhr</div><div id="event_text13"><br>Wir machen mit euch eine Zeitreise in die Steinzeit. Wir besuchen die Neanderthaler im Museum und sehen, wie die damaligen Menschen gelebt haben. Dann geht es durch den Wald zur Steinzeitwerkstatt, wo ihr das steinzeitliche Jagen mit Speeren ausprobiert und N&uuml;sse knacken lernt.<br>Nach einer kleinen Pause, in der ihr euch mit euren mitgebrachten Broten und Getr&auml;nken st&auml;rken k&ouml;nnt, stellen wir ein steinzeitliches Amulett aus Leder, einer Knochenperle und einer Muschel her. Das Amulett k&ouml;nnt ihr zur Erinnerung mit nach Hause nehmen.<br>reffpunkt: Eingangsfoyer des Neanderthal Museums, F&uuml;r Kinder ab 6 Jahre<br>Kosten: 24 &euro; inkl. Material und Eintritt<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 20, 2016';
Termin[Termin.length]='<div id="event_title14"><b>Steinzeit-Krimi</b><br>11.00-13.00 Uhr</div><div id="event_text14"><br>Ein fr&uuml;hmenschlicher Sch&auml;del wurde aus dem Museum gestohlen. Gemeinsam nehmt ihr die Ermittlungen nach der Diebesbande auf. Wer k&ouml;nnte das wertvolle St&uuml;ck gestohlen haben und wo befindet es sich jetzt? Die Mitarbeiter sind verzweifelt. K&ouml;nnt ihr helfen? Bei der interaktiven Verbrecherjagd m&uuml;ssen Spuren untersucht, knifflige R&auml;tsel gel&ouml;st und alle Hinweise schlau kombiniert werden. Eure Nachforschungen f&uuml;hren euch vom Museum und &uuml;ber das Au&szlig;engel&auml;nde durch den Wald zum spannenden Showdown. Ob ihr das Verbrechen aufkl&auml;ren k&ouml;nnt?<br>Treffpunkt: Eingangsfoyer des Neanderthal Museums F&uuml;r Kinder ab 8/9 Jahre, Dauer: 2 Stunde<br>Kosten: 16 &euro; inkl. Material und Eintritt<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 21, 2016';
Termin[Termin.length]='<div id="event_title15"><b>Mitmachf&uuml;hrung in der Dauerausstellung</b><br>11.00-12.00 Uhr</div><div id="event_text15"><br>Kommt mit zu den Neanderthalern. Wir besuchen sie an ihrem Lagerplatz und lernen die eiszeitlichen J&auml;ger und Sammler n&auml;her kennen. Wir sehen, welche Werkzeuge und Waffen sie benutzt haben, was ihre Lieblingsspeisen war, und welches Kleider sie getragen haben.<br>Das Beste an dieser Mitmachf&uuml;hrung ist aber zweifellos, dass ihr viele Objekte, beispielsweise einen echten Mammutzahn, in die Hand nehmen und untersuchen d&uuml;rft.<br>Treffpunkt: Eingangsfoyer des Neanderthal Museums F&uuml;r Kinder ab 6 Jahre, Dauer: 1 Stunde<br>Den Eintritt zahlt ihr direkt an der Museumskasse, die 4 &euro; f&uuml;r die F&uuml;hrung zahlt ihr bei der P&auml;dagogin/dem P&auml;dagogen.<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 21, 2016';
Termin[Termin.length]='<div id="event_title16"><b>Feuerstein - Schatz der Steinzeit</b><br>12.00-14.00 Uhr</div><div id="event_text16"><br>Ein Feuerstein war in der Steinzeit ein gro&szlig;er Schatz! Die Menschen stellten daraus wertvolle Werkzeuge und Waffen her, ohne die ihr &Uuml;berleben sicherlich deutlich schwerer gewesen w&auml;re. Mit Feuersteinen konnte man nicht nur Feuer machen, sondern auch Fell, Leder oder andere harte Materialien durchtrennen. Ihr lernt all diese M&ouml;glichkeiten des Feuersteins kennen, fertigt ein Steinzeitmesser an und graviert mit dem Feuerstein Bilder in Schiefer. Die Schieferplatte und das Steinzeitmesser k&ouml;nnt ihr mit nach Hause nehmen.<br>Treffpunkt: Steinzeitwerkstatt, F&uuml;r Kinder ab 8 Jahre, Dauer: 2 Stunde<br>Kosten: 16 &euro; inklusive Material<br>Bitte meldet euch verbindlich an: buchung@neanderthal.de, Tel.: 02104-979715</div>';

Termin[Termin.length]='October 27, 2016';
Termin[Termin.length]='<div id="event_title17"><b>Update: Humanevolution (Fortbildung)</b><br>09.30-17.00 Uhr</div><div id="event_text17"><br>Die Savannentheorie &uuml;berholt, die Neanderthaler als Geschwister des Homo sapiens sapiens identifiziert und neue Menschenarten in Indonesien und S&uuml;dsibirien entdeckt? In der wissenschaftlichen Forschung zur Humanevolution &uuml;berschlagen sich die Ereignisse. Als forschendes Museum sind wir nah an der wissenschaftlichen Diskussion, fasziniert von Funden und Objekten und gerne Ihr Partner bei der Vermittlung wissenschaftlicher Inhalte. Zum 20. Jubil&auml;um des Neanderthal Museums erwartet sie eine neu gestaltete Dauerausstellung, die von einer Reihe neuer Vorfahren bev&ouml;lkert wird.<br>Mit der Fortbildung wollen wir Sie darin unterst&uuml;tzen, den &Uuml;berblick &uuml;ber die aktuelle Forschung zur Humanevolution zu behalten und uns als Lernort f&uuml;r Ihre Sch&uuml;lerinnen und Sch&uuml;ler zu entdecken.<br>Tickets gibt es zum Preis von 17 &euro; f&uuml;r Fr&uuml;hbucher bis Montag, 10.10. und zu 23 &euro; f&uuml;r Kurzentschlossene ab Dienstag, 11.10. VVK an der Museumskasse und online zzgl. Geb&uuml;hren</div>';

Termin[Termin.length]='October 29, 2016';
Termin[Termin.length]='<div id="event_title18"><b>Bogenbauworkshop</b><br>09.00-18.00 Uhr</div><div id="event_text18"><br>Der Kursleiter Dr. Johann Tinnes baut seit vielen Jahren B&ouml;gen, Pfeile und Zubeh&ouml;r nach arch&auml;ologischen sowie v&ouml;lkerkundlichen Vorbildern und arbeitet f&uuml;r zahlreiche Museen.<br>In diesem Kurs besteht die M&ouml;glichkeit einen Bogen und zwei Pfeile unter fachkundiger Anleitung selber herzustellen. F&uuml;r die B&ouml;gen wird in der Regel Hickoryholz verwendet, f&uuml;r die Pfeile Kiefer oder Zeder (je nach Verf&uuml;gbarkeit). Zudem wird es eine Einf&uuml;hrung in die Handhabung des Bogens und ein Einschie&szlig;en geben.<br>Das Programm findet jeweils Samstag und Sonntag von 09.00 bis 18.00 Uhr statt.<br>Kosten: 200,– &euro; bis 350,– &euro;, abh&auml;ngig vom Bogentyp<br>Anmeldung: 0221.513877 / 0172.2435593, j.tinnes.pre-rec@arcor.de<br>Weitere Infos: http://www.pre-rec.de/index.html</div>';

Termin[Termin.length]='October 30, 2016';
Termin[Termin.length]='<div id="event_title19"><b>Bogenbauworkshop</b><br>09.00-18.00 Uhr</div><div id="event_text19"><br>Gefl&uuml;chtete f&uuml;hren durch die Dauerausstellung. Sie vermitteln fr&uuml;he Menschheitsgeschichte und erz&auml;hlen ihre eigenen Fluchtgeschichten. Wir sprechen beim Museumsrundgang &uuml;ber menschliche Migration, h&ouml;ren von den Fluchtwegen, anderen Religionen, anderen Kalendarien und lernen einige Worte auf Tigrinya.<br>3 &euro; + Eintritt, VVK an der Museumskasse oder online zzgl. Geb&uuml;hren</div>';

Termin[Termin.length]='October 30, 2016';
Termin[Termin.length]='<div id="event_title20"><b>Wege nach Europa. Gefl&uuml;chtete f&uuml;hren durch die Ausstellung</b><br>14.00-15.00 Uhr</div><div id="event_text20"><br>Der Kursleiter Dr. Johann Tinnes baut seit vielen Jahren B&ouml;gen, Pfeile und Zubeh&ouml;r nach arch&auml;ologischen sowie v&ouml;lkerkundlichen Vorbildern und arbeitet f&uuml;r zahlreiche Museen.<br>In diesem Kurs besteht die M&ouml;glichkeit einen Bogen und zwei Pfeile unter fachkundiger Anleitung selber herzustellen. F&uuml;r die B&ouml;gen wird in der Regel Hickoryholz verwendet, f&uuml;r die Pfeile Kiefer oder Zeder (je nach Verf&uuml;gbarkeit). Zudem wird es eine Einf&uuml;hrung in die Handhabung des Bogens und ein Einschie&szlig;en geben.<br>Das Programm findet jeweils Samstag und Sonntag von 09.00 bis 18.00 Uhr statt.<br>Kosten: 200,– &euro; bis 350,– &euro;, abh&auml;ngig vom Bogentyp<br>Anmeldung: 0221.513877 / 0172.2435593, j.tinnes.pre-rec@arcor.de<br>Weitere Infos: http://www.pre-rec.de/index.html</div>';



/* Zeichensatz beachten: Test nach Vokalen und Szett + Eurozeichen */